Repository SOPT-all/35-APPJAM-iOS-NAPZAKMARKET, pull requests merged in 2025-01, with the labels that each got.

#2 [Docs] #1 - 깃허브 기본 세팅
  .github/pull_request_template.md
  .gitignore
  README.md
Labels: Docs 📑, 혜린 🎀

#4 [Setting] #3 - 프로젝트 초기 세팅
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Napzakmarket-iOS/Napzakmarket-iOS/Application/Napzakmarket_iOSApp.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Application/Preview Content/Preview Assets.xcassets/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Literals/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Modifiers/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Fonts/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Network/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ContentView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Detail/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Detail/View/DetailView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/OnboardingView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Splash/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Splash/View/SplashView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabbarView.swift
Labels: Setting ⚙️, 혜린 🎀

#11 [Setting] #7 - 디자인 시스템 세팅
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/View+.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Literals/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Literals/ColorLiteral.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Literals/FontLiterial.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Modifiers/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Modifiers/NapzakTextStyleModifier.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Fonts/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Fonts/Pretendard-Bold.otf
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Fonts/Pretendard-Medium.otf
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Fonts/Pretendard-SemiBold.otf
  Napzakmarket-iOS/Napzakmarket-iOS/Info.plist
Labels: Setting ⚙️, 혜린 🎀

#10 [Style] #5 - Sell Register View UI 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/TextEditor+.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/TextField+.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/SellRegisterView.swift
Labels: Style 🖼️, 한열 🧄

#14 [Style] #6 Tabbar UI 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Application/Napzakmarket_iOSApp.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_buy.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_buy.imageset/ic_buy.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_chat.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_chat.imageset/ic_chat.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_chat_select.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_chat_select.imageset/ic_chat_select.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_home.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_home.imageset/ic_home.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_home_select.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_home_select.imageset/ic_home_select.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_look.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_look.imageset/ic_look.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_look_select.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_look_select.imageset/ic_look_select.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_my.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_my.imageset/ic_my.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_my_select.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_my_select.imageset/ic_my_select.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_register.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_register.imageset/ic_register.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_register_select.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_register_select.imageset/ic_register_select.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_sell.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Tabbar/ic_sell.imageset/ic_sell.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/Model/TabBarModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/ExtraView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/PreView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabBarView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabbarView.swift
Labels: Style 🖼️, 어진 🧸

#17 [Refactor] #13 - Sell Register View 컨벤션 맞춰서 수정
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/String+.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/TextEditor+.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/TextField+.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Literals/ColorLiteral.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_checkbox.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_checkbox.imageset/ic_checkbox.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_checkbox_selected.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_checkbox_selected.imageset/ic_checkbox_selected.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_photo.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_photo.imageset/ic_photo.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ContentView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Buy/RegisterBuyHeader.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterDescription.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterGenre.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterImage.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterTitle.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterDeliveryCharge.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterProductState.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterSellHeader.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterSellPrice.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/SellRegisterView.swift
Labels: Refactor 🏗️, 한열 🧄

#23 [Style] #9 - OnboardingView UI 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Application/Napzakmarket_iOSApp.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/SearchBar.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Onboarding/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Onboarding/btn_reset.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Onboarding/btn_reset.imageset/btn_reset.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Onboarding/img_onboarding_empty.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Onboarding/img_onboarding_empty.imageset/img_onboarding_empty.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Network/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Network/OnboardingMock/Base/APIResponse.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/OnboardingMock/Base/MockGenreError.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/OnboardingMock/Entities/Genre.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/OnboardingMock/MockGenreService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/OnboardingMock/Models/GenreModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/OnboardingMock/Resources/en.lproj/mock_genres_39.json
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/AppEntryView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/Model/GenreModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Chip/ChipsContainerView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Chip/GenreChip.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Genre/GenreCell.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Genre/GenreGridView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/OnboardingView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabBarView.swift
Labels: Feat 💻, 호근 🍙

#20 [Style] #15 - 탐색 탭 기본 UI 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductItemView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/SegmentedControl/NZSegmentedControl.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/icn_heart_list.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/icn_heart_list.imageset/icn_heart_list.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/icn_heart_list_select.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/icn_heart_list_select.imageset/icn_heart_list_select.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/img_tag_buy.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/img_tag_buy.imageset/img_tag_buy.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/img_tag_price_sm.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/img_tag_price_sm.imageset/img_tag_price_sm.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/img_tag_sell.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Component/img_tag_sell.imageset/img_tag_sell.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_genre.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_genre.imageset/chip_genre.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_soldout.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_soldout.imageset/chip_soldout.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_unopen.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_unopen.imageset/chip_unopen.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_down_sm_gray.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_down_sm_gray.imageset/icon_down_sm_gray.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_search.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_search.imageset/icon_search.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/Model/TabBarModel.swift
Labels: Style 🖼️, 혜린 🎀

#26 [Style] #18 - Buy Register View UI 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/SearchBar.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Buy/RegisterBuyHeader.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Buy/RegisterBuyPrice.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterGenre.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterSearch.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterDeliveryCharge.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterSellHeader.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabBarView.swift
Labels: Style 🖼️, 한열 🧄

#28 [Style] #24 - MarketView UI 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/Model/MarketModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/Model/TabBarModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/ReadyView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabBarView.swift
Labels: Chore 🪡, Style 🖼️, 어진 🧸

#29 [Feat] #27 - 등록 뷰 이미지 작업
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_x_circle_black.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_x_circle_black.imageset/ic_x_circle_black.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Buy/RegisterBuyHeader.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterGenre.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterImage.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterDeliveryCharge.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterSellHeader.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Model/RegisterModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/SellRegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabBarView.swift
Labels: Feat 💻, 한열 🧄

#30 [Refactor] #25 - 온보딩 UI 및 키보드 처리 개선
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Application/Napzakmarket_iOSApp.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/SearchBar.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Core/AppState.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Literals/ColorLiteral.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Animation/splash(ios).json
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/AppEntryView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Chip/ChipsContainerView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Genre/GenreGridView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/OnboardingView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Splash/View/SplashView.swift
Labels: Refactor 🏗️, Style 🖼️, 호근 🍙

#34 [Style] #32 -Chat UI 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Chat/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Chat/img_chat.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Chat/img_chat.imageset/img_chat.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Chat/View/ChatView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
Labels: Add ✚, Style 🖼️, 어진 🧸

#35 [Style] #22 - 탐색 탭 모달 UI 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_soldout_select.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_soldout_select.imageset/chip_soldout_select.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_unopen_select.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/chip_unopen_select.imageset/chip_unopen_select.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_check.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_check.imageset/icon_check.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_down_sm_white.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_down_sm_white.imageset/icon_down_sm_white.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_drag_indicator.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/icon_drag_indicator.imageset/icon_drag_indicator.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Chip/ChipsContainerView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Chip/GenreChip.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/OnboardingView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/Model/GenreSearchModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/Modal/GenreFilterModalView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/Modal/SortModalView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Splash/View/SplashView.swift
Labels: Style 🖼️, 혜린 🎀

#39 [Feat] #31 - 등록 정보 유효성검사와 등록 버튼 활성화
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Network/RegisterMock/DTO/SellRegisterRequest.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Buy/RegisterBuyHeader.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Buy/RegisterBuyPrice.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterDescription.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterGenre.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterImage.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterSearch.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterTitle.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterDeliveryCharge.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterProductState.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterSellHeader.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterSellPrice.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Model/RegisterModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/SellRegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabBarView.swift
Labels: Feat 💻, Fix 🔨, 한열 🧄

#45 [Style] #41 내마켓 모달 UI 추가
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/Modal/GenreFilterModalView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/Modal/SortModalView.swift
Labels: Chore 🪡, Style 🖼️, 어진 🧸

#46 [Fix] #42 - 등록과정에서 발견한 몇몇 에러나 매끄럽지 못 한 부분 수정
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_x_circle_black.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_x_circle_black.imageset/ic_x_circle_black.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_x_circle_black.imageset/ic_x_circle_black.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_x_circle_black.imageset/ic_x_circle_black@2x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Register/ic_x_circle_black.imageset/ic_x_circle_black@3x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterImage.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/SellRegisterView.swift
Labels: Fix 🔨, 한열 🧄

#48 [Refactor] #47 - 마이페이지 dto 생성
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/Model/MyPageFeature.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
Labels: Chore 🪡, Refactor 🏗️

#50 [Refactor] #43 - 온보딩 UI 개선
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_1.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_1.imageset/img_banner_1.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_1.imageset/img_banner_1.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_1.imageset/img_banner_1@2x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_1.imageset/img_banner_1@3x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_2.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_2.imageset/img_banner_1.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_2.imageset/img_banner_2.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_2.imageset/img_banner_2@2x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_banner_2.imageset/img_banner_2@3x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_1.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_1.imageset/img_home_1.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_1.imageset/img_home_1.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_1.imageset/img_home_1@2x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_1.imageset/img_home_1@3x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_2.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_2.imageset/img_home_2.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_2.imageset/img_home_2.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_2.imageset/img_home_2@2x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_2.imageset/img_home_2@3x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_3.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_3.imageset/img_home_3.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_3.imageset/img_home_3.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_3.imageset/img_home_3@2x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_home_3.imageset/img_home_3@3x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_logo.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_logo.imageset/img_logo.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_logo.imageset/img_logo.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_logo.imageset/img_logo@2x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Home/img_logo.imageset/img_logo@3x.png
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Genre/GenreGridView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/OnboardingView.swift
Labels: Refactor 🏗️, Style 🖼️, 호근 🍙

#53 [Feat] #37 - 탐색 탭 검색 뷰 구현
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/SearchBar.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/img_tag_genre.imageset/Contents.json
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Resources/Assets.xcassets/Search/img_tag_genre.imageset/img_tag_genre.svg
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/OnboardingView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterSearch.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/Modal/GenreFilterModalView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchInputView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
Labels: Feat 💻, Style 🖼️, 혜린 🎀

#59 [Network] #57 - 마이페이지 API 연결
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Base/NetworkService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/DTO/Response/MyPageInfoResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/DTO/Response/StoreInfoResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/StoreAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/StoreService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/Model/MyPageFeature.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
Labels: Network 📡, 어진 🧸

#62 [Network] #54 - 온보딩 API 연동 작업
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/Encodable+.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Base/NetworkService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Genre/DTO/Response/GenreNameResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Genre/DTO/Response/PreferGenreResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Genre/GenreService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/DTO/Response/BannerResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/StoreAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/StoreService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/Model/GenreModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Chip/ChipsContainerView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Chip/GenreChip.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Genre/GenreCell.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/Genre/GenreGridView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/OnboardingView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/Modal/GenreFilterModalView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
Labels: Network 📡, 호근 🍙

#65 [Network] #55 - 등록 API 작업(1)
  .gitignore
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Extensions/String+.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Info.plist
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Base/BaseTargetType.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Base/NetworkService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Presigned/DTO/Request/PresignedRequestDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Presigned/DTO/Response/PresignedResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Presigned/PresignedAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Presigned/PresignedService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/DTO/Request/RegisterProductRequestDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterGenre.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterImage.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterSearch.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Model/RegisterModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/BuyRegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/SellRegisterView.swift
Labels: Network 📡, 한열 🧄

#67 [Network] #63 - 홈화면 API 연결
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductItemView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/DTO/Response/BannerResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/DTO/Response/ProductResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/Model/.gitkeep
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/Model/HomeModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
Labels: Network 📡, 호근 🍙

#77 [Network] #68 - 상세 페이지 조회 API 연결
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductItemView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Literals/ColorLiteral.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/DTO/Response/ProductDetailResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/Model/ProductDetailModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
Labels: Network 📡, 혜린 🎀

#74 [Network] #73 - 마켓 상점정보/팔아요/구해요탭 API 연결
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/DTO/Response/MyPageInfoResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/DTO/Response/StoreInfoResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/StoreAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Store/StoreService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/Model/MarketModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
Labels: Network 📡, 어진 🧸

#75 [Refactor] #70 - 홈뷰 좋아요 버튼 개선 및 무한스크롤 구현
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/Model/GenreModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Onboarding/View/OnboardingView.swift
Labels: Refactor 🏗️, 호근 🍙

#83 [Fix] #79 - 자잘한 UI 개선 및 화면 연결
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Chat/View/ChatView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchInputView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
Labels: Fix 🔨, 혜린 🎀

#78 [Network] #66 - 등록 API 작업(2)
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Presigned/PresignedAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Presigned/PresignedService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/DTO/Request/RegisterProductRequestDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/DTO/Response/RegisterProductResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterSearch.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Model/RegisterModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
Labels: Network 📡, 한열 🧄

#81 [Network] #69 - 채팅뷰 API 연결
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/DTO/Response/ChatInfoResponseDTO.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Chat/Model/ChatModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Chat/View/ChatView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
Labels: Network 📡, 어진 🧸

#82 [Network] #76 - 상품아이템 좋아요 API 연결
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductItemView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/Model/ProductSearchModel.swift
Labels: Network 📡, 호근 🍙

#85 [Feat] #80 - [Feat] 등록완료 후 상품 상세페이지 이동
  Napzakmarket-iOS/Napzakmarket-iOS/Application/Napzakmarket_iOSApp.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Presigned/PresignedAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterImage.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterDeliveryCharge.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Model/RegisterModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/Model/TabBarModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabBarView.swift
Labels: Feat 💻, 한열 🧄

#86 [Network] #84 - 상품 상세 페이지 좋아요 API 연결 및 자잘한 UI 개선
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Core/AppState.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Base/NetworkService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Interest/InterestAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Interest/InterestService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Like/LikeAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Like/LikeService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductAPI.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Network/Product/ProductService.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/Model/ProductDetailModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/Modal/GenreFilterModalView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/Model/TabBarModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/PreView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/ReadyView.swift
Labels: Fix 🔨, Network 📡, 혜린 🎀

#94 [Fix] #91 - 1차 QA 반영
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Buy/RegisterBuyPrice.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/Sell/RegisterDeliveryCharge.swift
Labels: Fix 🔨, 한열 🧄

#96 [Fix] #92 - 디자인 QA
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/SegmentedControl/NZSegmentedControl.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/Model/TabBarModel.swift
Labels: Fix 🔨, 어진 🧸

#97 [Fix] #90 - 1차 QA 수정사항 반영
  Napzakmarket-iOS/Napzakmarket-iOS.xcodeproj/project.pbxproj
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/ProductItem/ProductItemView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Info.plist
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchInputView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
Labels: Fix 🔨, 혜린 🎀

#99 [Fix] #98 - 버그 해결
  Napzakmarket-iOS/Napzakmarket-iOS/Global/Components/SegmentedControl/NZSegmentedControl.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Chat/View/ChatView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Home/View/HomeView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Market/View/MarketView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Mypage/View/MypageView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/ProductDetail/View/ProductDetailView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterGenre.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Components/RegisterSearch.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/Model/RegisterModel.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Register/View/RegisterView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchInputView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Search/View/SearchView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/ReadyView.swift
  Napzakmarket-iOS/Napzakmarket-iOS/Presentation/Tabbar/View/TabBarView.swift
Labels: Fix 🔨, 혜린 🎀
